name: Upload Python Package to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is x86-64
        # macos-15 is aarch64
        os: [ubuntu-latest, macos-13, macos-15, windows-latest]
        architecture: [x86-64, aarch64]
        exclude:
          - os: windows-latest
            architecture: aarch64
          - os: macos-15
            architecture: x86-64
          - os: macos-13
            architecture: aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build with Maturin + sdist
        if: matrix.architecture == 'x86-64' && startsWith(matrix.os, 'ubuntu')
        run: |
          pip install "maturin>=1.9"
          cd ./crates/py-sugiyama
          maturin sdist -v
      - name: Build with Maturin + sdist
        run: |
          cd ./crates/py-sugiyama
          maturin build -v

      - name: Test wheel Unix
        # For linux; only test on x86-64 for now as this matches the runner architecture
        if: (matrix.architecture == 'x86-64' || startsWith(matrix.os, 'macos')) && !startsWith(matrix.os, 'windows')
        run: |
          pip install --force-reinstall --verbose ./target/wheels/*.whl
          python -c "from fast_sugiyama import from_edges; print(from_edges([(51, 50), (52, 51), (53, 50), (54, 51), (55, 50), (54, 50)]))"

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: fast_sugiyama-${{ matrix.os }}-${{ matrix.architecture }}
          path: ./target/wheels/
  publish:
    needs: [build-wheel]
    environment:
      name: pypi
      url: https://pypi.org/project/fast-sugiyama
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download sdists and wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verify-metadata: false
          verbose: true
