name: Python Lint & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build Python
        run: |
          pip install ruff
      - name: Lint
        run: |
          ruff check . --diff
          ruff format . --diff

  test:
    env:
      USING_COVERAGE: "3.13"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        include:
          - os: windows-latest
            python-version: "3.13"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test Coverage
        run: |
          pip install -e crates/py-sugiyama[test]
          pytest crates/py-sugiyama/ --cov --cov-branch --cov-config=crates/py-sugiyama/pyproject.toml
      - name: Upload coverage reports to Codecov
        if: (matrix.os == 'ubuntu-latest') && contains(env.USING_COVERAGE, matrix.python-version)
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
