name: Upload Python Package to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-24.04-arm,
            macos-13,
            macos-latest,
            windows-latest,
            windows-11-arm,
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build with Maturin
        run: |
          pip install -U "maturin>=1.9" setuptools wheel twine
          cd ./crates/py-sugiyama
          maturin build -v
          twine check --strict ../../target/wheels/*.whl
      - name: sdist with Maturin
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd ./crates/py-sugiyama
          maturin sdist -v
          twine check --strict ../../target/wheels/*.tar.gz
      - name: Test wheel
        run: |
          pip install --force-reinstall --verbose --find-links=./target/wheels/ fast-sugiyama
          python -c "from fast_sugiyama import from_edges; print(from_edges([(51, 50), (52, 51), (53, 50), (54, 51), (55, 50), (54, 50)]))"
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-fast_sugiyama-${{ matrix.os }}
          path: ./target/wheels/

  publish:
    needs: [build-wheel]
    environment:
      name: pypi
      url: https://pypi.org/project/fast-sugiyama
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download sdists and wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          skip-existing: true
